# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(verbose_name='\u043a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
