# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0004_auto_20180502_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': '\u0423\u0441\u043b\u0443\u0433\u0443', 'verbose_name_plural': '\u0423\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.Services', verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430'),
        ),
    ]
