# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0006_auto_20180502_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworks',
            name='alt',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
    ]
