# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0008_auto_20180505_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=50, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('image', models.ImageField(upload_to='services', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u0412\u0441\u043f\u043b\u044b\u0432\u0430\u044e\u0449\u0435\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u043e\u0439 \u0443\u0441\u043b\u0443\u0433\u0438')),
                ('alt', models.CharField(db_index=True, max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.Services', verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u0443',
                'verbose_name_plural': '\u041d\u0430\u0448\u0438 \u0440\u0430\u0431\u043e\u0442\u044b',
            },
        ),
    ]
