# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0009_servicedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0443\u0441\u043b\u0443\u0433', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0443\u0441\u043b\u0443\u0433'},
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image2',
            field=models.ImageField(default='', upload_to='services', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0432\u0442\u043e\u0440\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image3',
            field=models.ImageField(default='', upload_to='services', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0440\u0435\u0442\u044c\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='text2',
            field=models.TextField(default='', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u0430\u0431\u0437\u0430\u0446 \u0442\u0435\u043a\u0441\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
    ]
