# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0010_auto_20180518_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='services', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.Services', verbose_name='\u0423\u0441\u043b\u0443\u0433\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u0443\u0441\u043b\u0443\u0433\u0443',
            },
        ),
    ]
