# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0011_subservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservices',
            options={'verbose_name': '\u041f\u043e\u0434\u0443\u0441\u043b\u0443\u0433\u0430\u043c'},
        ),
    ]
