# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0012_auto_20180519_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservices',
            options={'verbose_name': '\u041f\u043e\u0434\u0443\u0441\u043b\u0443\u0433\u0443', 'verbose_name_plural': '\u041f\u043e\u0434\u0443\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='subservices',
            name='text',
            field=models.TextField(max_length=72, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
