# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 16:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0013_auto_20180523_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='text2',
            field=ckeditor.fields.RichTextField(verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u0430\u0431\u0437\u0430\u0446 \u0442\u0435\u043a\u0441\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
        ),
    ]
