# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0015_auto_20180621_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.Services', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
