# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180505_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430'},
        ),
    ]
